### ISSUE TITLE
Game crashes with HM06 Whirlpool

### ISSUE THREAD

**Issue by Natanaelsom** [KittyPBoxx/GBAXG#10]
I had an issue with the HM06 Whirlpool that caused my game to crash every time I openned my bag to learn the move.
It only occurred on Crystal Dust V2. The other games didn't even show the HM06 Whirlpool (I guess it was expected). After crashing and resetting a few times, the game started to crash while using warps.
I also had another unrelated issue that I wasn't able to open the basement door in Goldenrod Department Store. I had the basement key, but the door just wouldn't open. Maybe I missed something. Sorry if it was the case.

I would like to clarify that I don't know if these bugs were caused by the Map randomizer or by the Pokemon randomizer that I applied to the ROMs.
If you need more information, please, don't mind on sending me a message. I will give you as much information as I can provide.

**Comment by KittyPBoxx** [comment]
I'm not sure why the crashing would happen using warps but possibly after crashing a bunch the save states got mixed up? Sometimes you can recover from this by using the auto save. There's also an override if the game is still running but a warp failed, clicking on the screen will force it to try and load the next map.

I just tried out whirlpool and the basement key and they worked for me. I also know some people who were playing with randomizers over christmas and they didn't have any issues with these. 

---

To work out whats happening in your case can you let me know the following:

1.  Which version are you playing on? I'd expect it to say '1.0.4-ALPHA'  https://kittypboxx.github.io/GBAXG/skycore/build/bin/

2. If the game was crashing it's possible data was lost. Can you confirm you still had the basement key when you were trying to open the door?

3.  Are you using the randomizer from the patches tab? (https://kittypboxx.github.io/GBAXG/skycore/upr/UniversalPokemonRandomizer-gbaxg-0.11.3-alpha.zip). This is a special version of UPR modified to work with crystal dust and to allow you to use the same random seed for all the roms.

4. Are you using speedup? I recently fixed an issue using speedup could cause older saves to be loaded but there could be something I missed as not many people test this feature.

5. Are you playing on mobile or a tabled? I've had some reports that devices that can't run the game at full speed can fail to copy data between games (especially if the ultra speed patches are also being used). In the worst case scenario the player can loose their items, entire party and name. 

---

Additionally it would be helpful if you could provide an export of your save and your randomizer settings.

**Comment by Natanaelsom** [comment]
Thank you for the fast response!

I believe that the save states got mixed up, because some times the load from slot 1 stopped working and only the autosave worked. Then my game loaded in a warp that, the moment I entered a warp (I guess I only tried the same warp), I appeared again in the same spot, just for trying again and moving to the correct point.

About your questions, I guess I have good pieces of information that may lead to the root cause.

> 1. Which version are you playing on? I'd expect it to say '1.0.4-ALPHA' https://kittypboxx.github.io/GBAXG/skycore/build/bin/

I strongly believe I was playing on '1.0.4-ALPHA', however I started the game using the internet, exported the save and imported on another pc using the internet, and had no internet for the rest of the game, playing the same run through a couple of days (hibernating Windows a few times).

> 2. If the game was crashing it's possible data was lost. Can you confirm you still had the basement key when you were trying to open the door?

I can confirm. I checked that I had the key in front of the door. I was only able to check before the game starts to crash in warps. After the crash in warps, I was stuck in the same place.

> 3. Are you using the randomizer from the patches tab? (https://kittypboxx.github.io/GBAXG/skycore/upr/UniversalPokemonRandomizer-gbaxg-0.11.3-alpha.zip). This is a special version of UPR modified to work with crystal dust and to allow you to use the same random seed for all the roms.

In fact, I'm not! I tried using this randomizer, but it didn't work in the crystal dust. Maybe I did something wrong. I searched for another randomizer and used a randomizer that someone recommended. The randomizer worked and that is why I didn't use the Universal Randomizer. Also, I didn't know I should use the same random seed for all the ROMs. Maybe I should try this.

> 4. Are you using speedup? I recently fixed an issue using speedup could cause older saves to be loaded but there could be something I missed as not many people test this feature.

Yes, I used speedup. Mostly used the x2 speed. I started playing on December 26th using the internet, changed to another pc on the 27th using the internet and continued to play until the 29th without using internet.

> 5. Are you playing on mobile or a tabled? I've had some reports that devices that can't run the game at full speed can fail to copy data between games (especially if the ultra speed patches are also being used). In the worst case scenario the player can loose their items, entire party and name.

I played on a laptop only.

> Additionally it would be helpful if you could provide an export of your save and your randomizer settings.

Sure! 
[2023-12-29_15_35GBAXG_SAVE.zip](https://github.com/KittyPBoxx/GBAXG/files/13824580/2023-12-29_15_35GBAXG_SAVE.zip)
[WarpMapping_c7lx4b.json](https://github.com/KittyPBoxx/GBAXG/files/13824582/WarpMapping_c7lx4b.json)
[Randomizer Settings 02.zip](https://github.com/KittyPBoxx/GBAXG/files/13824587/Randomizer.Settings.02.zip)

**Comment by KittyPBoxx** [comment]
I don't think I read your first comment carefully enough. In Crystal Dust the basement key opens the door in GOLDENROD UNDERGROUND (not the department store).  This links to the department store basement but the metal door and storage crates block way. In normal crystal I think the crates get moved depending on time of day but I don't think this works in crystal dust. Going through goldenrod basement isn't required to beat the randomizer (or possible).   

---

It looks like the game was crashing trying to warp into crsytal while it was in a crashed state. I forced a reset which fixed the save and let me warp between games again.  With vanilla roms I was able to check that whirlpool and the basement key were working so I suspect the problem was how the randomizer randomized items in Crystal Dust. 

Normal UPR breaks with crystal dust. The special version I edited will show a warning but should work. You have to manually enter a seed at the box on the top left to get the same seed between games. This will mean your pokemon keep the same abilities between randomized games (although TMs/HM's will still change between games). I recommend not using any of the random exp curve stuff as different exp curves between games causes a lot of issues.  

Here's working version of your save I tested everything with. It should be safe if you want to use it, but you'll need to change the roms you have loaded (or items in crystal dust will probably crash again.).

[2024-01-04_00_45GBAXG_SAVE.zip](https://github.com/KittyPBoxx/GBAXG/files/13824672/2024-01-04_00_45GBAXG_SAVE.zip)

**Comment by Natanaelsom** [comment]
Thank you so much!
I will try the patched UPR and start a new game.

The only thing that is bothering me is that you said the Goldenrod Underground warp takes me to the Department Store Basement. In my run, I had a different warp leading to the Goldenrod Underground and didn't have any other warp leading to the Department Store Basement. In this version of Crystal, I was able to move the boxes just leaving the elevator in a different floor and going back, however the basement door did not open.

Just to further clarify, here is the door that I had trouble openning and the warp I wasn't able to reach.
![image](https://github.com/KittyPBoxx/GBAXG/assets/28265634/687dbae2-fbbe-448f-9c41-c6b48080d41d)

**Comment by KittyPBoxx** [comment]
I guess it must be possible to move the boxes then.  I wasn't sure because time based events weren't finished in V2. 

I meant that in un-randomized crystal it goes:
 underground door -> landing room -> rival battle room with switch doors ->  goes to the rival room with the doors  -> underground corridor -> department store basement.
 
There is an event trigger to open that door but I had issues with it in testing so the randomizer treats it as a dead-end. I guess it's still listed as a hub warp on the tracker.  I think the tracker map for this was last updated about a year ago and there have been a few changed, the main ones being 1) underwater warps are not randomized 2) two of the seafloor cavern rooms were removed.   
 
This is the door the basement key opens:
![basement](https://github.com/KittyPBoxx/GBAXG/assets/89883734/bbd515c6-53b7-4c61-8581-71f6b1b6672a)

Which you get from fighting the guy in the radio tower. Because the item slot is reused between Emerald and CrystalDust the same key can open the door to New Mauville (although this would be out of logic). And you can also get the key by speaking with Watson outside Mauville Pokecenter after beating Norman.
