### ISSUE TITLE
Softlock at Rocket HQ/Celadon gym

### ISSUE THREAD

**Issue by Pokededg** [KittyPBoxx/GBAXG#14]
I got a warp to the entrance of the Rocket HQ at Johto, which is locked until you talk to Lance at the Lake of Rage. However, the exit of that house is also locked as the exit is the Celadon Gym, for which you need cut to get out, something that I still don't have on my run. This would be a softlock if not for the option to warp to Pallet town.
![image](https://github.com/KittyPBoxx/GBAXG/assets/162046006/62e160dd-897e-4050-9e64-197c7161800c)
![image](https://github.com/KittyPBoxx/GBAXG/assets/162046006/dcad0b34-0ba5-4f57-9881-a811c8e84bbe)

**Comment by KittyPBoxx** [comment]
The mahogany stairs were missing a one-way tag. 

However I've had a few reports of people having problems with the stairs. I'm not sure if it's because people don't know how to trigger them or if there's a way players can lock themselves out of being able to talk to lance. 

Therefore, as of the latest changes the stairs will always be open.
