### ISSUE TITLE
Emulator opening into either Emerald or Crystal

### ISSUE THREAD

**Issue by rfbruce** [KittyPBoxx/GBAXG#7]
Tried out the emulator first in firefox and then switched over to chrome based on website page comments regarding speed up issues.
Initially everything loaded properly into fire red, got to Virdian and warp zones weren't set. So reloaded everything.

Cleared rom states, then added in fire red, crystal dust, and emerald. Start game / reset buttons weren't doing anything, clicking inside the emulator for the game screen caused a static image of entering mom's home in emerald to appear. Clicking fast forward then caused it to go from being static to playable and could switch back to regular speed and still play.

Investigating the player would already have a starter, mudkip, name would be ??? and warp was an option in the settings.
Clearing roms and repeating this process, but loading crystal dust last would then cause a static image of entering the new bark professor's lab to appear after clicking in the emulator game area that was previously all black.
Checking inventory showed a level 5 totadile, name as ???, and warp as an option.

Trying to load fire red last, doesn't seem to cause affect anything.

Troubleshooting steps involved was to remove any save file in the same folder as the .gba file used for the rom files.
Clearing rom states.
Clearing browser cache of everything.
Restarting computer.
Removing old rom files and getting fresh ones, including rebuilding crystal dust and checking the checksum values listed on the website. Only checksum checked was emerald, before patching crystal dust.

I can provide screen shots if needed.
It kind of feels like the files getting generated with the emerald and crystal dust are testing files used for testing warps and the like from different regions. I suspect that the emulator when loaded in my browser is pulling a file somewhere that probably just needs to be cleared out, but I'm not sure regarding how the browser emulator works with storing any files locally other than the base rom files that it pulls.

**Comment by KittyPBoxx** [comment]
'Clear Stored ROMS' from the ROMS tab only resets the roms. To clear save data you need to use the 'Clear Saves/ROMS' from the Saves tab. This should rest the state of the emulator so you can try loading the roms again from scratch.

To randomize loading zones you need to use the 'Randomize Warps' button in the warps tab. This can be done at any point and after you've done it once the warps will stay randomized even after you reaload.

---

To explain what I think happened with the games. When you load Emerald and Crystal Dust it creates a 'default' save file in those games (so when you enter those games for the first time you don't have to go through the intro). Whenever the emulator starts up after the game has been started it opens the last save file that was written to and boots that game. Because you reset Fire Red without ever saving or warping to another game no save file was ever created for Fire Red. 
The emulator knows you've started the game so it loading the latest save file (which is the default because there was no manual save made.)

---

If the save clear isn't working, to clear the emulator data manually  in Chrome you can use:
1. click the 3 dots > More Tools >  Developer Tools
2. Select the application tab
3. Expand 'IndexDB' in the Storage section on the left.
4. Expand /offline and click on 'FILE_DATA' then you can see and delete all the files the emulator created.

**Comment by rfbruce** [comment]
Thanks for the reply. The clear saves/ROMS under saves did indeed reset it. I assumed the clear stored ROMS did the same functionality of clearing so my bad for not realizing the difference. Definitely appreciate the assistance on your end.

I didn't save as I was checking it out, and assumed I would have to reset once or twice as I figured out the settings and getting everything setup. So I think your analysis is spot on that it was loading into the other default saves created to skip the intros and which one it would load into was dependent one which ROM was added last in the load sequence.

I also appreciate being able to know where to go to clear the data manually if it is ever needed.

I think both of your answers for the clearing option under saves and the manual approach would be great additions to the FAQ (even if it isn't a frequent question lol)
Might be a decent idea to add to the backlog of ideas that if no fire red save data is detected, but the save data for crystal / emerald is present, then run a clear of saves / rom data.

Again thanks for the quick reply and solution!

**Comment by KittyPBoxx** [comment]
I've added buttons so that the user can 'force-reboot' into whichever game they want. Hopefully it's not too confusing and  will give users the an extra tool to work around any problems they have. So I'm going to close the issue.

---

I've had a few people mention this now, it seems it's fairly common for people to check that it all works then come back later to play (only to find it's now loading a different game).

Save data detection is a little tricky because users might never save in Fire Red and do their first save after a warp. There should be a way to properly check but the 'smarter' I try and make the logic the more I seem to break things 

---
 
At some point I need to go back check the whole FAQ (and possibly remake tutorial video)  as it's a about a year old and the whole thing was re-written, almost from scratch since then
