### ISSUE TITLE
Possible softlock in seafloor cavern

### ISSUE THREAD

**Issue by Algo2121** [KittyPBoxx/GBAXG#8]
When I end up in the seafloor cavern (room 1) from the top . I had the strength HM, so I pushed down the rock and went the entrance and it was a dead end. When I got back there from the entrance, but I didn't have a rock smash HM and it's impossible to go back without it.
![1](https://github.com/KittyPBoxx/GBAXG/assets/119063147/a08c1fc3-6b18-454b-b07e-36da3759f3a9)
![2](https://github.com/KittyPBoxx/GBAXG/assets/119063147/90a7355b-15c4-41f3-aecf-d10e0059a8a9)

**Comment by KittyPBoxx** [comment]
Thanks, I'll look into it. 

Even though I've tried to reduce the chance of softlocks there are a few that slip in. In the menu there is a 'WARP' option that will take you back to palette town as a 'catch-all' for any case where someone gets stuck.

I suspect this case was overlooked because in normal Emerald map rando it's impossible to get strength without also having rock smash (from rusturf tunnel).

**Comment by KittyPBoxx** [comment]
This is finally fixed with the latest softlock prevention changes.
